### ISSUE TITLE
sets page: show names in bold

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson4-website#13]
For simple highlighting reasons the most important information on that page, the name of each set, should be bold.

**Comment by tooomm** [comment]
Somebody who can run the page locally could post some screens, I'm just assuming that it would be an improvement. Right now it blends all together and nothing stands out, so it would help with that.

**Comment by ZeldaZach** [comment]
Added in #17 :)

**Comment by tooomm** [comment]
Indeed, I think it looks better and more structured now! 👍 
Thanks you @ancestral for taking care. I like it.
