### ISSUE TITLE
documentation not up to date

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson4-website#18]
A lot of the recent changes are not documented yet.

**Comment by ZeldaZach** [comment]
They’re in the queue for V4.1 docs. Just not public yet.

**Comment by tooomm** [comment]
Yep, that was my assumption. Ticket can be considered a reminder.

**Comment by ancestral** [comment]
4.1 was updated. Please let me know if anything appears missing.

**Comment by fenhl** [comment]
The order of names for meld cards appears to be undocumented.

**Comment by ZeldaZach** [comment]
@fenhl Doc'd in changelog, but could prob be added to docs page

**Comment by fenhl** [comment]
The changelog should not be considered documentation. If important things are mentioned there but left out from the docs page, users may have to scroll through the changelog (which will only get longer over time) to find what they're looking for.

**Comment by fenhl** [comment]
Why is this closed? The missing documentation for meld card names has still not been addressed.

**Comment by tooomm** [comment]
Thanks @ancestral: https://github.com/mtgjson/mtgjson4-website/commit/18fc36b8e8d6c7cc074c9dc68986f495240860ad
