### ISSUE TITLE
Duplicated set file for download

### ISSUE THREAD

**Issue by estevaodias** [mtgjson/mtgjson4-website#21]
Hi, 

I found some duplicated sets here 

https://mtgjson.com/v4/sets.html#

They are 4ED.json, both for Fourth Edition and Foreign Black Border, PS14.json, in San Diego Comic-Con 2014 and Salvat 2011, and CON.json, in Conflux, is responding with 404. 

https://mtgjson.com/v4/json/CON.json

I hope I could contribute with this issue and thank you for the great job you'r doing :)

**Comment by ancestral** [comment]
Okay, I found the link for FBB bad, but I can’t confirm any others.
