### ISSUE TITLE
V3 -> V4 Changelog

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson4-website#8]
### Added:
- `meta` (Better understanding of when data was created)
- `mtgoCode` (Determine MTGO set name)
- `tokens` (Tokens have made it in!)
- `foilOnly` (If a set is available only in foil, like sliver premium deck)

### Removed:
- `gathererCode` (No longer necessary)
- `magicCardsInfoCode` (No longer in service)
- `border` (Moved to individual cards)
- `booster` (Will be re-added in v4.1)

### Added:
- `frameVersion` (Determine the frame type)
- `hasFoil` (Card available in foil)
- `hasNonFoil` (Card available in non-foil)
- `isOnlineOnly` (Card only available online)
- `isOversized` (Card is HUGEEE)
- `foreignData` (All foreign printings from the set and data relating)

### Removed:
- `source` (Hard to validate)
- `mciNumber` (No longer in service)
- `life` (Will re-add whenever Vanguard support is re-implemented)
- `hand` (Will re-add whenever Vanguard support is re-implemented)
- `imageName` (No longer a thing)
- `variations` (Each printing will have it's own entry)

### Changed:
- `cmc` is now `convertedManaCost`
- `convertedManaCost` is a float over an int
- `multiverseid` is now `multiverseId` (with capital I)
- `flavor` is now `flavorText`
- `border` is now `borderColor`
- `id` is now `uuid`
- `legalities` formatting has changed
- `loyalty` is now a string

**Comment by ancestral** [comment]
I think this looks great!

**Comment by tooomm** [comment]
This should be linked to from the webpage as well.

Here are the changes from the initial v4 try as reference, maybe there is a leftover and somebody can file an issue for important missing "features" for later?
https://github.com/mtgjson/mtgjson4_temporary#new-features-and-changes
I think stuff like changes to the filenames/merge of -x files should be listed here too.

>**New features and Changes**
>
>- Persistent immutable ID, generated for each card, stored on "_id" field.
>- JSON database stored on a different project
>- Sorting
>     - All objects with sorted keys
>     - Card arrays are sorted by number, then by multiverseid
>- Command line interface for adding, removing and querying substitution rules
>- Files provided on the website will be pretty-printed (instead of one-liners)
>- Incorporate tokens
>     - Tokens will also have unique "_id" fields.
>     - Tokens will have their own array, separated from the cards array.
>     - Tokens will have a "card generator" array, provided they are from the same set.
>     - Initially, tokens will be parsed from a sub-repo of the Cockatrice project:
>     - Cockatrice/Magic-Token:tokens.xml@master
>- Fields that will be removed:
>     - id
>     - imageName
>- Set Specific
>     - EMN
>          - Try to look for meld cards automatically with the "Melds with (card-name-here)." on text.
>- New provided files
>    - AllCards_Standard.json
>    - AllTokens.json
>- Filename alteration: the "-x" suffix will be changed to "-full".
>- Every file will have a ".sig" file as well.
